config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'analyses/index'
  root to: "analyses#index"
  resources :career_anchors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career_anchor.rb
class CareerAnchor < ApplicationRecord

  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :one_to_four

  validates :question_1, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_2, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_3, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_4, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_5, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_6, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_7, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_8, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_9, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_10, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_11, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_12, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_13, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_14, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_15, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_16, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_17, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_18, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_19, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_20, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_21, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_22, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_23, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_24, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_25, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_26, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_27, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_28, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_29, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_30, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_31, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_32, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_33, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_34, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_35, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_36, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_37, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_38, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_39, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
  validates :question_40, presence: true,numericality: { other_than: 0, message: "can't be blank" } 
end

app/models/one_to_four.rb
class OneToFour < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '全くそう思わない' },
    { id: 2, name: 'あまりそう思わない' },
    { id: 3, name: 'そう思うことが多い' },
    { id: 4, name: '全くその通りだと思う' },
  ]
  include ActiveHash::Associations
  has_many :career_anchors

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  
  validates :name, presence: true
  validates :company_name, presence: true
  validates :position, presence: true
  validates :occupation, presence: true

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は6文字以上かつ英数字をそれぞれ含めてください' }

end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :company_name, :position, :occupation])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/career_anchors_controller.rb
class CareerAnchorsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit, :destroy, :show]

  def index
    @career_anchor = CareerAnchor.all.order(created_at: :desc)
  end

  def new
    @career_anchor = CareerAnchor.new
  end

  def create 
    @career_anchor = CareerAnchor.new(career_anchor_params)
    if @career_anchor.save
      redirect_to career_anchors_path
    else
      render :new
    end
  end

  def show
    @career_anchor = CareerAnchor.find(params[:id])
    if @career_anchor.user_id == current_user.id || current_user.admin?
    else
    redirect_to root_path 
    end
  end

  def destroy
    @career_anchor = CareerAnchor.find(params[:id])
    if @career_anchor.user_id == current_user.id
     @career_anchor.destroy
    else
    redirect_to root_path
    end
  end

  def edit
    @career_anchor = CareerAnchor.find(params[:id])
    if @career_anchor.user_id == current_user.id
    else
    redirect_to root_path 
    end
  end

  def update
     @career_anchor = CareerAnchor.find(params[:id])
    if @career_anchor.update(career_anchor_params)
       redirect_to career_anchors_path
    else
      render :edit
    end
  end

  private
  def career_anchor_params
    params.require(:career_anchor).permit(
      :question_1, :question_2, :question_3, :question_4, :question_5, :question_6, :question_7, :question_8, :question_9, :question_10,
      :question_11, :question_12, :question_13, :question_14, :question_15, :question_16, :question_17, :question_18, :question_19, :question_20,
      :question_21, :question_22, :question_23, :question_24, :question_25, :question_26, :question_27, :question_28, :question_29, :question_30,
      :question_31, :question_32, :question_33, :question_34, :question_35, :question_36, :question_37, :question_38, :question_39, :question_40
      ).merge(user_id: current_user.id)
  end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/career_anchors_helper.rb
module CareerAnchorsHelper
end

app/views/analyses/index.html.erb
<h1>トップページ</h1>
<div>診断をする
  <ul>
    <li><%= link_to "自分の価値観を知ろう", new_career_anchor_path %></li>
    <%= "自分のキャリア選択において絶対に譲りたくない「大切なこと」を明確にします" %>
    <li>*******</li>
  </ul>
</div>
<div>結果を確認する
  <ul>
    <li> 
    <%= link_to "自分の価値観について", career_anchors_path,method: :get %>
    </li>
    <li>*******</li>
  </ul>
</div>

app/views/career_anchors/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">トップページへ戻る</a>
  </div>
</div>

app/views/career_anchors/index.html.erb
<h1>診断結果を見る</h1>  
<% @career_anchor.each do |career_anchor| %> 
<% if current_user.admin? %> 
    <li>
       <%= l career_anchor.created_at %>
       <%= link_to "#{career_anchor.user.name}さんの診断結果", career_anchor_path(career_anchor.id), method: :get %>
    </li> 
 <% elsif current_user.id == career_anchor.user_id %> 
    <li>
       <%= l career_anchor.created_at %>
       <%= link_to "#{career_anchor.user.name}さんの診断結果", career_anchor_path(career_anchor.id), method: :get %>
    </li> 
   <% elsif CareerAnchor.find_by(user_id: current_user.id) == nil %>
    <%= "診断結果はありません" %>
   <% break %>
  <% end %>
<% end %>

app/views/career_anchors/show.html.erb
<h1> 診断結果の表示 </h1>
<div class ="career_anchors_btn">
<% if @career_anchor.user_id == current_user.id %>
<h3 class =career_anchors_btn1>
<%= link_to "編集する", edit_career_anchor_path(@career_anchor.id), method: :get %></h3>
<h3><%= link_to "削除する", career_anchor_path(@career_anchor.id), method: :delete %></h3>
<% end %>
</div>

<% tf = @career_anchor.question_1 + @career_anchor.question_9 + @career_anchor.question_17 + @career_anchor.question_26 + @career_anchor.question_35 %>
<% gm = @career_anchor.question_2 + @career_anchor.question_10 + @career_anchor.question_21 + @career_anchor.question_30 + @career_anchor.question_36 %>
<% au = @career_anchor.question_3 + @career_anchor.question_11 + @career_anchor.question_18 + @career_anchor.question_31 + @career_anchor.question_38 %>
<% se = @career_anchor.question_5 + @career_anchor.question_12 + @career_anchor.question_19 + @career_anchor.question_25 + @career_anchor.question_37 %>
<% ec = @career_anchor.question_4 + @career_anchor.question_13 + @career_anchor.question_20 + @career_anchor.question_29 + @career_anchor.question_33 %>
<% sv = @career_anchor.question_7 + @career_anchor.question_14 + @career_anchor.question_22 + @career_anchor.question_28 + @career_anchor.question_34 %>
<% ch = @career_anchor.question_8 + @career_anchor.question_15 + @career_anchor.question_23 + @career_anchor.question_32 + @career_anchor.question_40 %>
<% ls = @career_anchor.question_6 + @career_anchor.question_16 + @career_anchor.question_24 + @career_anchor.question_27 + @career_anchor.question_39 %>
<%# column_chart [["専門職務別能力", th], ["経営管理能力", gm],["自律・独立", au], ["保障・安定", se],["起業家的創造性", ec], ["奉仕・社会貢献", sv],["純粋な挑戦", ch], ["生活様式", ls]] %>

<% tf_type = "特定の仕事に対する高い才能と意欲を持ち、専門家として能力を発揮することに満足と喜びを覚えるタイプです。
    自分の技能を応用し、技能を常に高いレベルに向上し続ける機会を大事にします。
    アイデンティティの感覚が自分の技能を実践することから生まれており、仕事で専門領域について挑戦し続けることが出来た時、
    最も喜びを感じることが出来ます。
    このタイプの人たちは、他の仕事に移ると、自分の能力があまり活かされないため、満足度が低下します。
    また、マネージャー職に対しても必ずしも魅力を感じません。マネージャーになると管理業務が主となるため、
    やはり自分の専門性が発揮できなくなるからです。"%>
<% gm_type = "経営者（ゼネラル・マネージャー）になることが価値あることと考え、経営者を目指すタイプです。
    部門を超えて人々の努力を統合し、担当ユニットの成果に責任を持つこと、いわゆる「出世志向」がある人たちです。
    1.の「専門・職種別」コンピタンスの人たちと異なり、専門能力の必要性は認められるものの、その専門性に特化することなく、
    企業経営に求められる全般的な能力の獲得を重視します。
    重い責務に対処するために必要な分析能力、対人スキル、対集団スキル、情報能力などを備えています。"%>
<% au_type ="どのような仕事であっても、自分のやり方、自分のペースを守って仕事を進めることを大切と考えるタイプです。
    従って、このタイプの人は集団駆動のための一定の規律が求められる企業組織に属することは好まず、
    独立の道を選ぶ傾向にあります。また、独立しないまでも、研究職など行動の自由度が高い職種が向いています。
    また、自律性を維持するために、昇進や出世の機会を断ることもあります。" %>
<% se_type ="安全・確実で、将来の変化を概ね予測でき、ゆったりとした気持ちで仕事をしたいと考えるタイプです。
    ほとんとdの人が、基本的には安定した仕事や報酬を求めます。最優先事項です。
    当然のことながら、終身雇用が期待できる企業への就職を望みます。財務的保障（年金や退職プランなど）と、雇用の安定です。" %>
<% ec_type ="新しい製品、サービスを開発したり、資金を調達して組織を立ち上げたり、既存事業を買収して再建する
    といったことに燃えるタイプです。危険や障害を乗り越えていく意欲と、自分の能力だけに頼って、
    組織や企業を創造する機会と考えます。具体的には、発明家、芸術家、あるいはアントレプレナー（起業家）を
    目指す人たちが該当します。このタイプの人たちは、結果的に独立、企業する道を選びます。
    3.の「自律・独立」タイプの人と異なり、何か新しいこと（事業や作品など）を生み出すといった創造性の
    発揮を重視しています。そのためには、自律・独立性を犠牲にすることもいといません。" %>
<% sv_type ="何らかの形で、世の中を良くしたいという価値観を重視するタイプです。環境問題を解決すること、
    人々に調和をもたらすこと、誰かを助けること、安全性を向上させること、新製品を通じて病気を治すことなどといった、
    何か価値のあるものを実現したいと願っています。医療、介護、社会福祉、教育などの分野を目指す人が該当します。
    近年注目を集めている「社会起業家」（ソーシャル・アントレプレナー）は、社会問題を営利事業を通じて
    解決していくことを目的とする人たちです。彼らにとって大事なのは、社会貢献であり、事業を立ち上げることは、
    そのための手段に過ぎません。従って、5.の「起業家的創造性」のタイプとは志向が異なります。" %>
<% ch_type ="不可能と思えるような障害を乗り越えること、解決不能と思われてきた問題を解決することなどを追求して
    やまないタイプです。常にあえて「困難」を探し求めているため、特定の仕事や専門性にこだわりません。
    「挑戦」自体が人勢のテーマなのです。相手との競争に「純粋な挑戦」を見い出します。新寄性、多様性、困難が目的であり、簡単だとすぐに飽きてしまいます。" %>
<% ls_type ="仕事と家庭生活、公的な仕事の時間と私的な個人の時間のどちらも大切にしたいと願い、両者の適切なバランスを
    考えているタイプです。仕事に打ち込む一方、例えば子供が生まれたら、育児休暇をしっかり取り、子育ても大切にする
    という生き方を積極的に志向します。ワークライフバランス（仕事とそれ以外の人生、つまり家庭や娯楽などでうまく
    バランスを取ろうという考え方）は、このタイプの人にとって一番大切なことです。" %>

<% type = [["専門・職能別能力タイプ", tf], ["経営管理能力タイプ", gm],["自律・独立タイプ", au], ["保障・安定タイプ", se],["起業家的創造性タイプ", ec], ["奉仕・社会貢献タイプ", sv],["純粋な挑戦タイプ", ch], ["生活様式タイプ", ls]]%>
<% type_dsc =  type.sort_by { |_, v| -v }.to_h %>
<%= column_chart type_dsc %>

<% type_dsc["専門・職能別能力タイプ"] = tf_type%>
<% type_dsc["経営管理能力タイプ"] = gm_type%>
<% type_dsc["自律・独立タイプ"] = au_type%>
<% type_dsc["保障・安定タイプ"] = se_type%>
<% type_dsc["起業家的創造性タイプ"] = ec_type%>
<% type_dsc["奉仕・社会貢献タイプ"] = sv_type%>
<% type_dsc["純粋な挑戦タイプ"] = ch_type%>
<% type_dsc["生活様式タイプ"] = ls_type%>

<h2> あなたのタイプ（上位３つ）</h2>
<div class = type-3>
<h3 class = type-key><%= "一つは「#{type_dsc.keys[0]}」"%><br></h3>
<div class = type-value ><%= "#{type_dsc.values[0]}" %><br></div>
<h3 class = type-key><%= "一つは「#{type_dsc.keys[1]}」"%><br></h3>
<div class = type-value ><%= "#{type_dsc.values[1]}" %><br></div>
<h3 class = type-key><%= "一つは「#{type_dsc.keys[2]}」"%><br></h3>
<div class = type-value ><%= "#{type_dsc.values[2]}" %><br></div>
</div>

<h2>全タイプの詳細</h2>
  <ul>
    <li class = "type">1.専門・職能別能力(Technical/Functional Competence :TF)　◆職人</li>
    <div class = "type-box"> 
    <%= tf_type %>
    </div>
    <li class = "type">2.経営管理能力(General Managerial Competence :GM)　◆幹事</li>
    <div class = "type-box">
     <%= gm_type %>
    </div>
    <li class = "type">3.自律・独立(Autonomy/Independence :AU)　◆自由人</li>
    <div class = "type-box">
      <%= au_type %>
    </div>
    <li class = "type">4.保障・安定(Security/Stability :SE)　◆組織人</li>
    <div class = "type-box">
      <%= se_type %>
    </div>
    <li class = "type">5.起業家的創造性(Entrepreneurial Creativity :EC)　◆新価値創造</li>
    <div class = "type-box">
      <%= ec_type %>
    </div>
    <li class = "type">6.奉仕・社会貢献(Service/Dedication toa Cause :SV)　◆社会派</li>
    <div class = "type-box">
       <%= sv_type %>
    </div>
    <li class = "type">7.純粋な挑戦(Pure Challenge :CH)　◆チャレンジャー</li>
    <div class = "type-box">
       <%= ch_type %>
    </div>
    <li class = "type">8.生活様式(Lifestyle :LS)　◆バランサー</li>
    <div class = "type-box">
      <%= ls_type %>
    </div>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnalysisApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <header class="header">
    <div class="header__bar row">
      <% if user_signed_in? %>
          <li><%= link_to "ようこそ #{current_user.name} さん", "#", class: "header-left"%> </li>
          <div class="header-right2">
          <li><%= link_to "トップページへ", root_path, class:"header-right2"%> </li>
          </div>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "header-right" %> </li>
        <% else %>
          <div class="header-right2">
          <li><%= link_to 'ログイン', new_user_session_path, class: "header-right2" %></li>
          </div>
          <li><%= link_to '新規登録', new_user_registration_path, class: "header-right" %></li>
      <% end %>
    </div>
  </header>
  <%= yield %>
   <footer>
      <p>
        AnalysisApp 2022.
      </p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>